name: GitAction CI/CD

on: 
    push:
          branches:
          - main

jobs:
      runs-ci:
        runs-on: ubuntu-latest

        steps:
        - name: Ambil code paling baru
          uses: actions/checkout@v3

        - name: Install PHP
          uses: shivammathur/setup-php@v2
          with: 
            php-version: "8.1"

        - name: Install Composer
          run: |
            composer install --no-scripts

        - name: Jalan Unit Test
          run: |
              php artisan test
